#!/usr/bin/env bash
cd "$(dirname "$0")/.."

have() { command -v "$1" >/dev/null 2>&1; }

if [[ "$TRAVIS" == "true" ]]; then
  if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    echo "This is a pull request. No deployment will be done."
    exit 0
  fi
  if [[ "$TRAVIS_RUBY_VERSION" != "1.9.3" ]]; then
    echo "Testing on something other than 1.9.3. No deployment will be done."
    exit 0
  fi
  if [[ "$TRAVIS_BRANCH" != "master" ]]; then
    echo "Testing on a branch other than master. No deployment will be done."
    exit 0
  fi

  wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

  if ! have heroku; then
    echo "The heroku toolbelt is not installed. Please install it: https://toolbelt.heroku.com."
    exit 1
  fi

  heroku plugins:install https://github.com/ddollar/heroku-anvil
fi

heroku build -r shoes-cedar -b https://github.com/heroku/heroku-buildpack-ruby.git

